import type { NextPage } from 'next'
import Head from 'next/head'
import { Form, ResultDisplay } from '../components/ui'
import styles from '../styles/Home.module.css'
const Home: NextPage = () => {
  return (
    <div className={styles.root}>
      <Head>
        <title>An Application called Google Cloud Functions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>An Application called Google Cloud Functions</h1>
        <Form />
        <ResultDisplay />

      </main>

      </div>
  )
}

export default Home
